- 👋 Hi, I’m @Brenda-k25
- 👀 I’m interested in data analysis
- 🌱 I’m currently learning web development and gaining more experience in data science
- 💞️ I’m looking to collaborate on my projects with other programmers to acquire more exposure
- 📫 How to reach me :kithuabrenda@gmail.com
- 😄 Pronouns: ~~
- ⚡ Fun fact: I love reading 

<!---
Brenda-k25/Brenda-k25 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
